import type { RouteManifestEntry } from './types'

export const API_ROUTE_MANIFEST: RouteManifestEntry[] = [
    { endpoint: '/api/admin/billing/invoices/backfill', method: 'POST' },
    { endpoint: '/api/admin/billing/invoices', method: 'GET' },
    { endpoint: '/api/admin/billing/webhook-events', method: 'GET' },
    { endpoint: '/api/admin/dashboard', method: 'GET' },
    { endpoint: '/api/admin/delivery-orders/[id]', method: 'GET' },
    { endpoint: '/api/admin/delivery-orders/[id]', method: 'PATCH' },
    { endpoint: '/api/admin/delivery-orders/[id]', method: 'POST' },
    { endpoint: '/api/admin/delivery-orders', method: 'GET' },
    { endpoint: '/api/admin/orders/[id]', method: 'GET' },
    { endpoint: '/api/admin/orders/[id]', method: 'PATCH' },
    { endpoint: '/api/admin/orders', method: 'GET' },
    { endpoint: '/api/admin/products/[id]', method: 'GET' },
    { endpoint: '/api/admin/products/[id]', method: 'PATCH' },
    { endpoint: '/api/admin/products/[id]', method: 'DELETE' },
    { endpoint: '/api/admin/products/export', method: 'GET' },
    { endpoint: '/api/admin/products/import', method: 'POST' },
    { endpoint: '/api/admin/products/media-upload', method: 'POST' },
    { endpoint: '/api/admin/products', method: 'GET' },
    { endpoint: '/api/admin/products', method: 'POST' },
    { endpoint: '/api/admin/subscriptions/[id]', method: 'GET' },
    { endpoint: '/api/admin/subscriptions/[id]', method: 'PATCH' },
    { endpoint: '/api/admin/subscriptions/[id]', method: 'POST' },
    { endpoint: '/api/admin/subscriptions', method: 'GET' },
    { endpoint: '/api/admins', method: 'GET' },
    { endpoint: '/api/admins', method: 'POST' },
    { endpoint: '/api/admins', method: 'PATCH' },
    { endpoint: '/api/admins', method: 'DELETE' },
    { endpoint: '/api/billing/catalog/sync', method: 'POST' },
    { endpoint: '/api/billing/checkout', method: 'POST' },
    { endpoint: '/api/billing/config', method: 'GET' },
    { endpoint: '/api/bundles/[id]', method: 'GET' },
    { endpoint: '/api/bundles/[id]', method: 'PATCH' },
    { endpoint: '/api/bundles/[id]', method: 'DELETE' },
    { endpoint: '/api/bundles', method: 'GET' },
    { endpoint: '/api/bundles', method: 'POST' },
    { endpoint: '/api/customers', method: 'GET' },
    { endpoint: '/api/customers', method: 'DELETE' },
    { endpoint: '/api/orders', method: 'GET' },
    { endpoint: '/api/products/[id]', method: 'GET' },
    { endpoint: '/api/products/[id]', method: 'PATCH' },
    { endpoint: '/api/products/[id]', method: 'DELETE' },
    { endpoint: '/api/products', method: 'GET' },
    { endpoint: '/api/products', method: 'POST' },
    { endpoint: '/api/profile', method: 'GET' },
    { endpoint: '/api/profile', method: 'POST' },
    { endpoint: '/api/profile', method: 'PATCH' },
    { endpoint: '/api/setup-admin', method: 'GET' },
    { endpoint: '/api/subscriptions/[id]', method: 'GET' },
    { endpoint: '/api/subscriptions/[id]', method: 'PATCH' },
    { endpoint: '/api/subscriptions', method: 'GET' },
    { endpoint: '/api/subscriptions', method: 'POST' },
    { endpoint: '/api/webhooks/stripe', method: 'POST' },
]

export function toRouteMethodKey(entry: RouteManifestEntry) {
    return `${entry.method} ${entry.endpoint}`
}

